// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQxUvH4pM-YVYCH7cobLQXrxXSAaaqx1w',
    appId: '1:557144253448:web:62f522c8bb117160ebddbd',
    messagingSenderId: '557144253448',
    projectId: 'flutterapp-59169',
    authDomain: 'flutterapp-59169.firebaseapp.com',
    storageBucket: 'flutterapp-59169.appspot.com',
    measurementId: 'G-VDZKNZ545J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-d3Emorpb0ytrcRWrMnCqjqcGPIKhsmQ',
    appId: '1:557144253448:android:45ec8e8cc02e3e40ebddbd',
    messagingSenderId: '557144253448',
    projectId: 'flutterapp-59169',
    storageBucket: 'flutterapp-59169.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr9sWYRVRAKRss_gw5qSh1m2Me992L2Xs',
    appId: '1:557144253448:ios:d8916bc6a7e82755ebddbd',
    messagingSenderId: '557144253448',
    projectId: 'flutterapp-59169',
    storageBucket: 'flutterapp-59169.appspot.com',
    iosClientId: '557144253448-lb1uiam98b780ehuvtj78op1k42j5kdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicatEafit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr9sWYRVRAKRss_gw5qSh1m2Me992L2Xs',
    appId: '1:557144253448:ios:d8916bc6a7e82755ebddbd',
    messagingSenderId: '557144253448',
    projectId: 'flutterapp-59169',
    storageBucket: 'flutterapp-59169.appspot.com',
    iosClientId: '557144253448-lb1uiam98b780ehuvtj78op1k42j5kdi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicatEafit',
  );
}
